# Generated by Django 4.1.3 on 2023-01-16 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_email', models.EmailField(max_length=254)),
                ('sender_email', models.EmailField(max_length=254)),
                ('email_type', models.IntegerField(choices=[(1, 'EMAIL VERIFY'), (2, 'FORGET PASSWORD')])),
                ('email_content', models.CharField(max_length=50000)),
                ('email_subject', models.CharField(max_length=200)),
                ('email_detail', models.CharField(max_length=500)),
                ('is_send', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EmailVerifyToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=50)),
                ('expire_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
