# Generated by Django 4.1.3 on 2022-12-10 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom_member',
            name='role',
            field=models.CharField(choices=[('muted', 'muted'), ('creator', 'creator'), ('member', 'member'), ('admin', 'admin')], default='member', max_length=10),
        ),
    ]
