# Generated by Django 4.1.3 on 2023-01-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_chatroom_member_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom_member',
            name='role',
            field=models.CharField(choices=[('muted', 'muted'), ('admin', 'admin'), ('member', 'member'), ('creator', 'creator')], default='member', max_length=10),
        ),
    ]
